version: '3.7'

services:
  nuxt:
    restart: always
    build:
      context: .
      dockerfile: ./configs/nuxt.dockerfile
    env_file:
      - .env
    networks:
      reverse:
        aliases:
        - riotstats_nuxt
    volumes:
      - ./nuxt:/app

  api:
    image: abiosoft/caddy:no-stats
    restart: always
    networks:
      backend:
      reverse:
        aliases:
          - riotstats
    volumes:
      - ./api:/app
      - caddy-data:/root/.caddy
      - ./configs/Caddyfile:/etc/Caddyfile

  postgres:
    image: postgres:12-alpine
    restart: always
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./configs/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  adminer:
    image: adminer
    restart: always
    networks:
      backend:
      reverse:
        aliases:
          - riotstats_adminer

  redis:
    image: redis
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - backend

  php:
    build:
      context: .
      dockerfile: ./configs/php.dockerfile
    restart: always
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - ./api:/app
      - ./nuxt/static:/app/storage/app/sitemap

  queue:
    build:
      context: .
      dockerfile: ./configs/php.dockerfile
    restart: always
    env_file:
      - .env
    environment:
      CONTAINER_ROLE: queue
    networks:
      - backend
    volumes:
      - ./api:/app

  cron:
    build:
      context: .
      dockerfile: ./configs/php.dockerfile
    restart: always
    env_file:
      - .env
    environment:
      CONTAINER_ROLE: cron
    networks:
      - backend
    volumes:
      - ./api:/app

networks:
  backend:
  reverse:
    external:
      name: caddy_reverse

volumes:
  db-data:
  redis-data:
  caddy-data:
  postgres-data:
